### ISSUE TITLE
Flake8 failures in TravisCI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.StandardCacheManagers#4]
Example: https://travis-ci.org/github/zopefoundation/Products.StandardCacheManagers/jobs/733660534

**Comment by jugmac00** [comment]
`isort` is not pinned and got updated to `5.5.4` 

One of the reasons I really like `pre-commit` for running linters.

**Comment by dataflake** [comment]
I still don't see the connection between precommit and pinning isort. That can be pinned anywhere. And using precommit will not magically fix the code in the package.
